openapi: 3.0.3
info:
  title: Employee Management API
  version: 1.0.0
  description: API for managing employees

tags:
  - name: Employees
    description: Employee management operations

paths:
  /employees:
    get:
      summary: Get all employees
      description: Retrieve all employees (Admin, Team Leader, HR Manager only)
      tags: [Employees]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - Insufficient permissions

    post:
      summary: Create a new employee
      description: Create a new employee (Admin, HR Manager only)
      tags: [Employees]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEmployeeRequest"
      responses:
        "201":
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "400":
          description: Validation error
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - Insufficient permissions

  /employees/{id}:
    get:
      summary: Get employee by ID
      description: Get employee details (Admin, Team Leader, HR Manager, or own profile)
      tags: [Employees]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Employee ID
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Employee details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - Access denied
        "404":
          description: Employee not found

    put:
      summary: Update employee
      description: Update employee details (Admin, HR Manager, or own profile)
      tags: [Employees]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Employee ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEmployeeRequest"
      responses:
        "200":
          description: Employee updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "400":
          description: Validation error
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - Access denied
        "404":
          description: Employee not found

    delete:
      summary: Delete employee
      description: Delete employee (Admin only)
      tags: [Employees]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Employee ID
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Employee deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Employee deleted successfully"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - Admin access required
        "404":
          description: Employee not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Employee:
      type: object
      properties:
        id:
          type: string
          description: Employee unique identifier (cuid)
        employeeCode:
          type: string
          description: Unique employee code
        firstName:
          type: string
          description: Employee first name
        lastName:
          type: string
          description: Employee last name
        phoneNumber:
          type: string
          nullable: true
          description: Employee phone number
        dateOfBirth:
          type: string
          format: date-time
          nullable: true
          description: Employee date of birth
        address:
          type: string
          nullable: true
          description: Employee address
        emergencyContact:
          type: object
          nullable: true
          description: Emergency contact information (JSON)
        hireDate:
          type: string
          format: date-time
          description: Employee hire date
        terminationDate:
          type: string
          format: date-time
          nullable: true
          description: Employee termination date
        departmentId:
          type: string
          description: Reference to department
        positionId:
          type: string
          description: Reference to position
        managerId:
          type: string
          nullable: true
          description: Reference to manager employee
        scheduleType:
          type: string
          enum: [FULL_TIME, PART_TIME, CONTRACT, TEMPORARY, INTERN]
          default: FULL_TIME
          description: Work schedule type
        hourlyRate:
          type: number
          format: decimal
          nullable: true
          description: Hourly rate (Decimal 10,2)
        salary:
          type: number
          format: decimal
          nullable: true
          description: Annual salary (Decimal 12,2)
        isAvailable:
          type: boolean
          default: true
          description: Employee availability status
        priority:
          type: integer
          default: 1
          description: Employee priority level
        blockedAt:
          type: string
          format: date-time
          nullable: true
          description: When employee was blocked
        blockedReason:
          type: string
          nullable: true
          description: Reason for blocking employee
        userId:
          type: string
          description: Reference to user account (unique)
        createdAt:
          type: string
          format: date-time
          description: Record creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Record last update timestamp
        createdBy:
          type: string
          nullable: true
          description: User who created the record
        updatedBy:
          type: string
          nullable: true
          description: User who last updated the record

    CreateEmployeeRequest:
      type: object
      required:
        [
          email,
          username,
          password,
          firstName,
          lastName,
          departmentId,
          positionId,
        ]
      properties:
        # User fields
        email:
          type: string
          format: email
          description: User email (unique)
        username:
          type: string
          description: Username (unique)
        password:
          type: string
          minLength: 6
          description: User password (will be hashed)
        # Employee fields
        firstName:
          type: string
          description: Employee first name
        lastName:
          type: string
          description: Employee last name
        phoneNumber:
          type: string
          description: Employee phone number
        dateOfBirth:
          type: string
          format: date-time
          description: Employee date of birth
        address:
          type: string
          description: Employee address
        employeeCode:
          type: string
          description: Employee Code
        emergencyContact:
          type: object
          description: Emergency contact JSON object
          example:
            name: "John Doe"
            relationship: "Spouse"
            phone: "+1-555-0123"
        hireDate:
          type: string
          format: date-time
          description: Employee hire date (defaults to now)
        departmentId:
          type: string
          description: Department ID (must exist)
        positionId:
          type: string
          description: Position ID (must exist)
        managerId:
          type: string
          description: Manager employee ID
        scheduleType:
          type: string
          enum: [FULL_TIME, PART_TIME, CONTRACT, TEMPORARY, INTERN]
          default: FULL_TIME
          description: Work schedule type
        hourlyRate:
          type: number
          format: decimal
          description: Hourly rate (Decimal 10,2)
        salary:
          type: number
          format: decimal
          description: Annual salary (Decimal 12,2)
        priority:
          type: integer
          default: 1
          description: Employee priority level

    UpdateEmployeeRequest:
      type: object
      description: All fields are optional for updates
      properties:
        # User fields
        email:
          type: string
          format: email
          description: User email (must be unique)
        username:
          type: string
          description: Username (must be unique)
        # Employee fields
        firstName:
          type: string
          description: Employee first name
        lastName:
          type: string
          description: Employee last name
        phoneNumber:
          type: string
          description: Employee phone number
        dateOfBirth:
          type: string
          format: date-time
          description: Employee date of birth
        address:
          type: string
          description: Employee address
        emergencyContact:
          type: object
          description: Emergency contact JSON object
        hireDate:
          type: string
          format: date-time
          description: Employee hire date
        terminationDate:
          type: string
          format: date-time
          description: Employee termination date
        departmentId:
          type: string
          description: Department ID (must exist)
        positionId:
          type: string
          description: Position ID (must exist)
        managerId:
          type: string
          description: Manager employee ID
        scheduleType:
          type: string
          enum: [FULL_TIME, PART_TIME, CONTRACT, TEMPORARY, INTERN]
          description: Work schedule type
        hourlyRate:
          type: number
          format: decimal
          description: Hourly rate (Decimal 10,2)
        salary:
          type: number
          format: decimal
          description: Annual salary (Decimal 12,2)
        priority:
          type: integer
          description: Employee priority level
