openapi: 3.0.3
info:
  title: Employee Manager API - Orders
  version: 1.0.0
  description: Orders, Assignments, OrderAssignments, Qualifications, and Ratings management API

servers:
  - url: http://localhost:3000/api/orders

paths:
  /:
    get:
      summary: Get all orders
      tags: [Orders]
      security: [ { bearerAuth: [] } ]
      responses:
        "200":
          description: List of all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      summary: Create a new order
      tags: [Orders]
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderInput"
      responses:
        "201":
          description: Created order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /{id}:
    get:
      summary: Get order by ID
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    put:
      summary: Update an order
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderInput"
      responses:
        "200":
          description: Updated order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    delete:
      summary: Delete an order
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      responses:
        "204":
          description: Deleted successfully

  /{id}/status:
    patch:
      summary: Update order status
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/OrderStatusEnum"
      responses:
        "200":
          description: Updated order status

  /{id}/summary:
    get:
      summary: Get order summary
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      responses:
        "200":
          description: Order summary
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /{orderId}/assignments:
    get:
      summary: Get assignments for an order
      tags: [Assignments]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      responses:
        "200":
          description: List of assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Assignment"
    post:
      summary: Create assignment for an order
      tags: [Assignments]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAssignmentInput"
      responses:
        "201":
          description: Created assignment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Assignment"

  /{orderId}/assignments/auto:
    post:
      summary: Auto-assign employees to order with intelligent matching
      tags: [Assignments]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AutoAssignConfig"
      responses:
        "200":
          description: Auto-assignment result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutoAssignResult"
        "400":
          description: Auto-assignment failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }

  /assignments/{id}:
    put:
      summary: Update assignment
      tags: [Assignments]
      parameters:
        - $ref: "#/components/parameters/AssignmentId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAssignmentInput"
      responses:
        "200":
          description: Updated assignment
    delete:
      summary: Delete assignment
      tags: [Assignments]
      parameters:
        - $ref: "#/components/parameters/AssignmentId"
      responses:
        "204":
          description: Deleted successfully

  /assignments/{id}/status:
    patch:
      summary: Update assignment status
      tags: [Assignments]
      parameters:
        - $ref: "#/components/parameters/AssignmentId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/AssignmentStatusEnum"
      responses:
        "200":
          description: Updated assignment status

  /{orderId}/order-assignments:
    get:
      summary: Get order assignments
      tags: [OrderAssignments]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      responses:
        "200":
          description: List of order assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderAssignment"
    post:
      summary: Create order assignment
      tags: [OrderAssignments]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderAssignmentInput"
      responses:
        "201":
          description: Created order assignment

  /order-assignments/{id}:
    delete:
      summary: Delete order assignment
      tags: [OrderAssignments]
      parameters:
        - $ref: "#/components/parameters/OrderAssignmentId"
      responses:
        "204":
          description: Deleted successfully

  /{orderId}/qualifications:
    get:
      summary: Get qualifications for order
      tags: [Qualifications]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      responses:
        "200":
          description: List of qualifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderQualification"
    post:
      summary: Create order qualification
      tags: [Qualifications]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderQualificationInput"
      responses:
        "201":
          description: Created qualification

  /order-qualifications/{id}:
    delete:
      summary: Delete order qualification
      tags: [Qualifications]
      parameters:
        - $ref: "#/components/parameters/OrderQualificationId"
      responses:
        "204":
          description: Deleted successfully

  /{orderId}/ratings:
    get:
      summary: Get ratings for an order
      tags: [Ratings]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
        - name: employeeId
          in: query
          schema:
            type: string
            format: cuid
        - name: customerId
          in: query
          schema:
            type: string
            format: cuid
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/RatingStatusEnum"
      responses:
        "200":
          description: List of ratings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderRating"
    post:
      summary: Create rating for an order
      tags: [Ratings]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: cuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRatingInput"
      responses:
        "201":
          description: Created rating

  /ratings/{id}:
    patch:
      summary: Update rating
      tags: [Ratings]
      parameters:
        - $ref: "#/components/parameters/RatingId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderRatingInput"
      responses:
        "200":
          description: Updated rating
    delete:
      summary: Delete rating
      tags: [Ratings]
      parameters:
        - $ref: "#/components/parameters/RatingId"
      responses:
        "204":
          description: Deleted successfully

components:
  parameters:
    OrderId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: cuid
    AssignmentId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: cuid
    OrderAssignmentId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: cuid
    OrderQualificationId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: cuid
    RatingId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: cuid

  schemas:
    OrderStatusEnum:
      type: string
      enum: [DRAFT, OPEN, ACTIVE, IN_PROGRESS, COMPLETED, CANCELLED, EXPIRED]
    AssignmentStatusEnum:
      type: string
      enum: [ASSIGNED, ACTIVE, COMPLETED, CANCELLED, OVERDUE]
    RatingStatusEnum:
      type: string
      enum: [EXCELLENT, GOOD, NEEDS_IMPROVEMENT]

    CreateOrderInput:
      type: object
      properties:
        orderNumber: { type: string }
        title: { type: string }
        description: { type: string }
        scheduledDate: { type: string, format: date-time }
        startTime: { type: string, format: date-time }
        endTime: { type: string, format: date-time }
        duration: { type: integer }
        location: { type: string }
        requiredEmployees: { type: integer, default: 1 }
        priority: { type: integer, default: 1 }
        specialInstructions: { type: string }
        status: { $ref: "#/components/schemas/OrderStatusEnum" }
        customerId: { type: string, format: cuid }

    UpdateOrderInput:
      allOf:
        - $ref: "#/components/schemas/CreateOrderInput"

    Order:
      type: object
      properties:
        id: { type: string, format: cuid }
        orderNumber: { type: string }
        title: { type: string }
        description: { type: string }
        status: { $ref: "#/components/schemas/OrderStatusEnum" }
        scheduledDate: { type: string, format: date-time }

    Assignment:
      type: object
      properties:
        id: { type: string, format: cuid }
        employeeId: { type: string, format: cuid }
        startDate: { type: string, format: date-time }
        endDate: { type: string, format: date-time }
        estimatedHours: { type: number }
        actualHours: { type: number }
        notes: { type: string }
        status: { $ref: "#/components/schemas/AssignmentStatusEnum" }

    CreateAssignmentInput:
      type: object
      properties:
        employeeId: { type: string, format: cuid }
        startDate: { type: string, format: date-time }
        endDate: { type: string, format: date-time }
        estimatedHours: { type: number }
        notes: { type: string }

    UpdateAssignmentInput:
      type: object
      properties:
        startDate: { type: string, format: date-time }
        endDate: { type: string, format: date-time }
        estimatedHours: { type: number }
        actualHours: { type: number }
        notes: { type: string }
        status: { $ref: "#/components/schemas/AssignmentStatusEnum" }

    OrderAssignment:
      type: object
      properties:
        id: { type: string, format: cuid }
        employeeId: { type: string, format: cuid }
        role: { type: string }
        hourlyRate: { type: number }

    CreateOrderAssignmentInput:
      type: object
      properties:
        employeeId: { type: string, format: cuid }
        role: { type: string }
        hourlyRate: { type: number }

    OrderQualification:
      type: object
      properties:
        id: { type: string, format: cuid }
        qualificationId: { type: string, format: cuid }
        required: { type: boolean, default: true }
        minProficiency: { type: integer, default: 1 }

    CreateOrderQualificationInput:
      type: object
      properties:
        qualificationId: { type: string, format: cuid }
        required: { type: boolean }
        minProficiency: { type: integer }

    OrderRating:
      type: object
      properties:
        id: { type: string, format: cuid }
        employeeId: { type: string, format: cuid }
        customerId: { type: string, format: cuid }
        rating: { type: integer, minimum: 1, maximum: 5 }
        comment: { type: string }
        category: { type: string }
        status: { $ref: "#/components/schemas/RatingStatusEnum" }
        ratedBy: { type: string }

    CreateOrderRatingInput:
      type: object
      properties:
        employeeId: { type: string, format: cuid }
        customerId: { type: string, format: cuid }
        rating: { type: integer, minimum: 1, maximum: 5 }
        comment: { type: string }
        category: { type: string }
        status: { $ref: "#/components/schemas/RatingStatusEnum" }
        ratedBy: { type: string }

    UpdateOrderRatingInput:
      type: object
      properties:
        rating: { type: integer, minimum: 1, maximum: 5 }
        comment: { type: string }
        category: { type: string }
        status: { $ref: "#/components/schemas/RatingStatusEnum" }

    AutoAssignConfig:
      type: object
      properties:
        maxEmployees: { type: integer, minimum: 1, maximum: 20 }
        requireAllQualifications: { type: boolean, default: true }
        minPerformanceScore: { type: number, minimum: 0, maximum: 100, default: 0 }
        excludeEmployeeIds: { type: array, items: { type: string, format: cuid } }
        prioritizePerformance: { type: boolean, default: true }

    AutoAssignResult:
      type: object
      properties:
        message: { type: string }
        assignments: 
          type: array
          items:
            $ref: "#/components/schemas/Assignment"
        summary:
          type: object
          properties:
            requested: { type: integer }
            assigned: { type: integer }
            criteria:
              type: object
              properties:
                requiredQualifications: { type: array, items: { type: string } }
                performanceFilter: { type: string }
                availabilityCheck: { type: boolean }
                conflictCheck: { type: boolean }

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
