-- Add missing values to ActivityType enum
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CONTAINER_UNLOADING';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CONTAINER_LOADING';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ASSEMBLY';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DISASSEMBLY';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CLEANING';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INSPECTION';
